### ISSUE TITLE
query 14

### ISSUE THREAD

**Issue by IvanValentini** [PlazaCommunity/resources#10]
Sono d'accordo con la soluzione proposta, ma dal momento che la consegna chiede: "**For each continent**, find the capacity" ritengo che ci debba essere una colonna per il continent

**Comment by Lollixzc** [comment]
Siamo 100% sicuri che "For each continent" implica il fatto di dover aggiungere il nome? (mi sembra di far logica)

**Comment by IvanValentini** [comment]
Si: https://didatticaonline.unitn.it/dol/mod/forum/discuss.php?d=195021#p406277

**Comment by Lollixzc** [comment]
Perfect, grazie
