### ISSUE TITLE
query 14

### ISSUE THREAD

**Issue by giuliapaternolli** [PlazaCommunity/resources#12]
L'assignment dice: "Non integer numbers must be rounded at the second decimal. Example 0.1234 → 0.12." 
Quindi i numeri che sono già interi possiamo lasciarli come sono o dobbiamo trasformarli in .00?
Si parla solo di quelli non interi quindi per quelli interi va bene lasciarli così

**Comment by Lollixzc** [comment]
Bah, se fai ROUND() ti sistema tutto lui. Alla fine basta che non ci siano più di 2 numeri decimali

**Comment by IvanValentini** [comment]
https://didatticaonline.unitn.it/dol/mod/forum/discuss.php?d=195021#p408065
