### ISSUE TITLE
Query 6

### ISSUE THREAD

**Issue by Lollixzc** [PlazaCommunity/resources#25]
La query 6 non mi risulta empty, in realtà ricevo 192 righe. Any suggestion? Oppure non è ancora stata fornita una soluzione?

**Comment by DaviDev-k** [comment]
Da quanto mi risulta in questo database non sono presenti nazioni che hanno solo stadi con capacità maggiore di 100000, quindi il risultato è necessariamente empty.
Fai attenzione agli ordini di grandezza, anche se modificandoli non sono riuscito ad ottenere 192 righe:
- \> 100000 = 10^5
- < 10000​ = 10^4

**Comment by Lollixzc** [comment]
Mhhh ricontrollo che abbia scritto giusto
