### ISSUE TITLE
query 7

### ISSUE THREAD

**Issue by matteo-crypto** [PlazaCommunity/resources#9]
A me risulta:
"Cyprus"
"Turkey"
"Switzerland"
"Faroe Islands"
"Hungary"
"Russia"
"Luxembourg"
"Czech Republic"
"Norway"
"Armenia"
"Netherlands"
"Montenegro"
"Austria"
"Ireland"
"San Marino"
"Portugal"
"Malta"
"Albania"
"Ukraine"
"Lithuania"
"Bulgaria"
"Liechtenstein"
"Croatia"
"Latvia"
"Slovenia"
"Azerbaijan"
"Greece"
"North Macedonia"
"Georgia"
"Belgium"
"Moldova"
"Estonia"
"Slovakia"
"Guernsey"
"Kazakhstan"
"Poland"
"Iceland"
"Kosovo"
"Denmark"
"Bosnia and Herzegovina"
"Republic of Abkhazia"
Tenendo conto che con giocato in casa intendiamo che una squadra ha giocato in uno stadio che appartiene alla nazione di appartenenza (esempio: l'Italia che gioca una partita a San Siro) e che anche un guest può essere considerato come giocante in casa se si gioca in uno stadio della sua nazione (es: home ->Germania, guest-> Italia, stadio -> San Siro).

**Comment by giuliapaternolli** [comment]
Ma a San Siro non può essere home la Germania, la squadra in casa è sempre quella della nazionalità dello stadio.

**Comment by matteo-crypto** [comment]
@giuliapaternolli 
Inizialmente pensavo anch'io così.
"Ma a San Siro non può essere home la Germania, la squadra in casa è sempre quella della nazionalità dello stadio." questo, purtroppo, deriva da un'incomprensione dal fatto che loro usano home e guest per le squadre.
A Brugnara gli è stato chiesto:
"E' corretto assumere che per ogni partita il country della squadra che gioca in casa è lo uguale al country dello stadio in cui si gioca la partita?" e lui ha risposto: "NO".
Quindi, vedila come se fosse squadra1, squadra2 anziché home, guest.
Se vuoi, stessa cosa la si ha con la tabella Nationality, che sarebbe dovuta chiamarsi Nation.

**Comment by IvanValentini** [comment]
Io credo che per squadra che gioca in casa si intenda la squadra che si trova nella colonna "home" e non alto.
Il country non c'entra nulla dal momento il country dello stadio in cui si gioca la partita, il country della squadra che gioca in casa e fuori casa possono essere tutti diversi.
Avevo chiesto una cosa simile sul forum
https://didatticaonline.unitn.it/dol/mod/forum/discuss.php?d=195021#p404325

**Comment by IvanValentini** [comment]
Detto questo, non sono d'accordo con la tua soluzione, ma ho come risultato 0 righe.

**Comment by matteo-crypto** [comment]
@IvanValentini 
Alla domanda
"Quindi anche un guest può essere considerato come giocante in casa se si gioca in uno stadio della sua nazione (es: home ->Germania, guest-> Italia, stadio -> San Siro)?" posta sul forum Brugnara ha risposto "corretto"

**Comment by mgiacopu** [comment]
> "Quindi anche un guest può essere considerato come giocante in casa se si gioca in uno stadio della sua nazione (es: home ->Germania, guest-> Italia, stadio -> San Siro)?" posta sul forum, Brugnara ha risposto "corretto".

Dunque si puó semplificare in "Squadre europee che non hanno mai giocato in uno stadio del loro paese" se ho inteso bene dalle risposte sul forum.

**Comment by IvanValentini** [comment]
Qui la situazione cambia. Grazie per avermelo fatto notare. Allora in generale valgono le seguenti cose:
1. Immaginare le colonne guest e home come squadra1 e squadra2
2. Questa condizione vale sempre per ogni match: (Squadra2.Country = Stadium.Country OR Squadra1.Country = Stadium.Country)
2a. Se SquadraX.Country = Stadium.Country allora SquadraX gioca in casa.
E corretto?

Se è corretto ho provato a riscrivere la query e mi viene come risultato 33 righe.
Sempre se le 3 cose dette sopra sono vere, la soluzione di  @matteo-crypto nonè corretta perché se per esempio prendi la Bosnia and Herzegovina vedi che esiste un Match svoltosi al "Gradski Stadion" il giorno "2021-03-31" alle "15:00:28", ma lo stadio si trova in Bosnia and Herzegovina e quindi la squadra Bosnia and Herzegovina giocava in casa e non rispetta le richieste della query.

Il risultato che ho ottenuto dalla mia query è il seguente:
"Armenia"
"Austria"
"Azerbaijan"
"Belgium"
"Bulgaria"
"Cyprus"
"Czech Republic"
"Denmark"
"Estonia"
"Faroe Islands"
"Greece"
"Guernsey"
"Hungary"
"Iceland"
"Ireland"
"Kazakhstan"
"Kosovo"
"Latvia"
"Liechtenstein"
"Lithuania"
"Luxembourg"
"Malta"
"Moldova"
"Montenegro"
"Netherlands"
"North Macedonia"
"Norway"
"Republic of Abkhazia"
"Russia"
"San Marino"
"Slovakia"
"Slovenia"
"Ukraine"

**Comment by matteo-crypto** [comment]
@IvanValentini 
Corretto punti 1 e 2.
Corretto il tuo output.
Avevo un piccolo baco nella mia query.

**Comment by Lollixzc** [comment]
Ragazzi a me non tornano i risultati: io trovo che solo Republic of Abkhazia non gioca in casa... Avete tenuto conto di tutte le cose dette dal prof?

**Comment by IvanValentini** [comment]
Io faccio riferimento al documento 'query.pdf' che è stato mandato sul gruppo telegram. Mi risultano 36 righe, che sono 3 righe in più di quanto avevo prima perché non tenevo conto di:
-'Si devono stampare anche i teams che non hanno uno stadio nella loro nazione di appartenenza, e che quindi non possono mai giocare in "casa" '
Questo è il risultato che ho ottenuto.
 country|
| :---- |
|Armenia|
|Austria|
|Azerbaijan|
|Belgium|
|Bulgaria|
|Cambodia|
|Cyprus|
|Czech Republic|
|Denmark|
|Dominica|
|Estonia|
|Faroe Islands|
|Greece|
|Guernsey|
|Hungary|
|Iceland|
|Ireland|
|Kazakhstan|
|Kosovo|
|Kyrgyzstan|
|Latvia|
|Liechtenstein|
|Lithuania|
|Luxembourg|
|Malta|
|Moldova|
|Montenegro|
|Netherlands|
|North Macedonia|
|Norway|
|Republic of Abkhazia|
|Russia|
|San Marino|
|Slovakia|
|Slovenia|
|Ukraine|

**Comment by Lollixzc** [comment]
Credo che i tre in più che hai trovato ci siano continenti extra-EU, lo considererei un errore. Io invece ho trovato l'errore che avevo nella mia query e mi risulta con le 33 righe della soluzione

**Comment by matteo-crypto** [comment]
33 dovrebbe essere corretto 👍

**Comment by Lollixzc** [comment]
Chiudo, mi pare corretta la soluzione proposta dopo una analisi con altre persone

**Comment by IvanValentini** [comment]
> @IvanValentini Credo che i tre in più che hai trovato ci siano continenti extra-EU, lo considererei un errore. Io invece ho trovato l'errore che avevo nella mia query e mi risulta con le 33 righe della soluzione.

Hai completamente ragione
